# Generated by Django 5.1.5 on 2025-01-26 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('fonctionnalites', models.JSONField(verbose_name='Features')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele_modifie', models.CharField(max_length=255, verbose_name='Modified Model')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('details', models.TextField(verbose_name='Details')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Name')),
                ('adresse', models.TextField(verbose_name='Address')),
                ('nombre_appartements', models.IntegerField(verbose_name='Number of Apartments')),
                ('superficie_totale', models.FloatField(verbose_name='Total Area')),
                ('date_construction', models.DateField(verbose_name='Construction Date')),
                ('nombre_etages', models.IntegerField(verbose_name='Number of Floors')),
                ('zones_communes', models.TextField(verbose_name='Common Areas')),
                ('date_dernier_controle', models.DateField(blank=True, null=True, verbose_name='Last Inspection Date')),
                ('type_chauffage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Heating Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_residences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coproprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coproprietaire_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('residence', models.ManyToManyField(blank=True, related_name='coproprietaire_residences', to='dashboard.residence', verbose_name='Residences')),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Number')),
                ('superficie', models.FloatField(verbose_name='Area')),
                ('occupation', models.CharField(choices=[('Propriétaire', 'Owner'), ('Locataire', 'Tenant'), ('Vacant', 'Vacant')], max_length=50, verbose_name='Occupation')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.coproprietaire', verbose_name='Owner')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.residence', verbose_name='Building')),
            ],
        ),
        migrations.CreateModel(
            name='Superadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='SuperSyndic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('superadmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_supersyndics', to='dashboard.superadmin', verbose_name='SuperAdmin')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersyndic_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='superadmin',
            name='supersyndics',
            field=models.ManyToManyField(blank=True, related_name='managed_by_superadmins', to='dashboard.supersyndic', verbose_name='SuperSyndics'),
        ),
        migrations.AddField(
            model_name='residence',
            name='supersyndic',
            field=models.ManyToManyField(blank=True, related_name='supersyndic_residences', to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersyndic_coproprietaires', to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.CreateModel(
            name='Syndic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('superadmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_syndics', to='dashboard.superadmin', verbose_name='SuperAdmin')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='superadmin',
            name='syndics',
            field=models.ManyToManyField(blank=True, related_name='managed_by_superadmins', to='dashboard.syndic', verbose_name='Syndics'),
        ),
        migrations.AddField(
            model_name='residence',
            name='syndic',
            field=models.ManyToManyField(blank=True, related_name='syndic_residences', to='dashboard.syndic', verbose_name='Syndic'),
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('supersyndic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supersyndic', verbose_name='SuperSyndic')),
                ('syndic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.syndic', verbose_name='Syndic')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('fonctionnalites_personnalisees', models.JSONField(blank=True, null=True, verbose_name='Custom Features')),
                ('est_personnalise', models.BooleanField(default=True, verbose_name='Is Custom')),
                ('license_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='dashboard.licensebase', verbose_name='Base License')),
                ('supersyndic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersyndic_licenses', to='dashboard.supersyndic', verbose_name='Super Syndic')),
                ('syndic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_licenses', to='dashboard.syndic', verbose_name='Syndic')),
            ],
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_coproprietaires', to='dashboard.syndic', verbose_name='Syndic'),
        ),
    ]
