# Generated by Django 5.1.3 on 2025-01-04 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='immeuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.immeuble', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='occupation',
            field=models.CharField(choices=[('Propriétaire', 'Owner'), ('Locataire', 'Tenant'), ('Vacant', 'Vacant')], max_length=50, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.coproprietaire', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='superficie',
            field=models.FloatField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='syndic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.syndic', verbose_name='Syndic'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coproprietaire_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='adresse',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='date_construction',
            field=models.DateField(verbose_name='Construction Date'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='date_dernier_controle',
            field=models.DateField(blank=True, null=True, verbose_name='Last Inspection Date'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='nombre_appartements',
            field=models.IntegerField(verbose_name='Number of Apartments'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='nombre_etages',
            field=models.IntegerField(verbose_name='Number of Floors'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='superficie_totale',
            field=models.FloatField(verbose_name='Total Area'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='syndic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.syndic', verbose_name='Syndic'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='type_chauffage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heating Type'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='zones_communes',
            field=models.TextField(verbose_name='Common Areas'),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='est_personnalise',
            field=models.BooleanField(default=True, verbose_name='Is Custom'),
        ),
        migrations.AlterField(
            model_name='license',
            name='fonctionnalites_personnalisees',
            field=models.JSONField(blank=True, null=True, verbose_name='Custom Features'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='dashboard.licensebase', verbose_name='Base License'),
        ),
        migrations.AlterField(
            model_name='license',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersyndic_licenses', to='dashboard.supersyndic', verbose_name='Super Syndic'),
        ),
        migrations.AlterField(
            model_name='license',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_licenses', to='dashboard.syndic', verbose_name='Syndic'),
        ),
        migrations.AlterField(
            model_name='licensebase',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='licensebase',
            name='fonctionnalites',
            field=models.JSONField(verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='licensebase',
            name='nom',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='modificationlog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='modificationlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='modificationlog',
            name='details',
            field=models.TextField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='modificationlog',
            name='modele_modifie',
            field=models.CharField(max_length=255, verbose_name='Modified Model'),
        ),
        migrations.AlterField(
            model_name='modificationlog',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='syndic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.syndic', verbose_name='Syndic'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='supersyndic',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supersyndic',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supersyndic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersyndic_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='syndic',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='syndic',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='syndic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
