# Generated by Django 5.1.3 on 2024-11-24 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='immeuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_dashboard.immeuble'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_dashboard.coproprietaire'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='syndic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_dashboard.syndic'),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='syndic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_dashboard.syndic'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='apps_dashboard.licensebase'),
        ),
        migrations.AlterField(
            model_name='license',
            name='super_syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_syndic_licenses', to='apps_dashboard.supersyndic'),
        ),
        migrations.AlterField(
            model_name='license',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_licenses', to='apps_dashboard.syndic'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='syndic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_dashboard.syndic'),
        ),
    ]
