# Generated by Django 5.1.5 on 2025-01-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='residence',
            field=models.ManyToManyField(blank=True, related_name='prestataire_residences', to='dashboard.residence', verbose_name='Residences'),
        ),
    ]
