# Generated by Django 5.1.4 on 2025-01-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='dashboard.syndic', verbose_name='Syndic'),
        ),
    ]
