# Generated by Django 5.1.3 on 2025-01-10 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_appartement_immeuble_alter_appartement_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coproprietaire',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.syndic', verbose_name='Syndic'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.syndic', verbose_name='Syndic'),
        ),
    ]
