# Generated by Django 5.1.5 on 2025-01-28 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_prestataire_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coproprietaire',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersyndic_coproprietaires', to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syndic_coproprietaires', to='dashboard.syndic', verbose_name='Syndic'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.syndic', verbose_name='Syndic'),
        ),
    ]
