# Generated by Django 5.1.4 on 2025-01-17 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_residence_supersyndic_alter_residence_syndic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='supersyndics',
            field=models.ManyToManyField(blank=True, related_name='managed_by_superadmins', to='dashboard.supersyndic', verbose_name='SuperSyndics'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='syndics',
            field=models.ManyToManyField(blank=True, related_name='managed_by_superadmins', to='dashboard.syndic', verbose_name='Syndics'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
