# Generated by Django 5.1.5 on 2025-01-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_coproprietaire_supersyndic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coproprietaire',
            name='supersyndic',
        ),
        migrations.RemoveField(
            model_name='coproprietaire',
            name='syndic',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='supersyndic',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='syndic',
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='supersyndic',
            field=models.ManyToManyField(blank=True, related_name='supersyndic_coproprietaires', to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='syndic',
            field=models.ManyToManyField(blank=True, related_name='syndic_coproprietaires', to='dashboard.syndic', verbose_name='Syndic'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='supersyndic',
            field=models.ManyToManyField(blank=True, related_name='supersyndic_prestataires', to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='syndic',
            field=models.ManyToManyField(blank=True, related_name='syndic_prestataires', to='dashboard.syndic', verbose_name='Syndic'),
        ),
    ]
