# Generated by Django 5.1.3 on 2025-01-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_coproprietaire_supersyndic_prestataire_supersyndic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Immeuble',
            new_name='Residence',
        ),
    ]
