# Generated by Django 5.1.4 on 2025-01-18 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_superadmin_supersyndics_superadmin_syndics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersyndic',
            name='superadmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_supersyndics', to='dashboard.superadmin', verbose_name='SuperAdmin'),
        ),
        migrations.AddField(
            model_name='syndic',
            name='superadmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_syndics', to='dashboard.superadmin', verbose_name='SuperAdmin'),
        ),
    ]
