# Generated by Django 5.1.5 on 2025-01-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_coproprietaire_supersyndic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supersyndic',
            name='superadmin',
        ),
        migrations.RemoveField(
            model_name='syndic',
            name='superadmin',
        ),
    ]
