# Generated by Django 5.1.4 on 2025-01-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_supersyndic_superadmin_syndic_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='residence',
            name='date_construction',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='residence',
            name='date_dernier_controle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nombre_appartements',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nombre_etages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='residence',
            name='superficie_totale',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='residence',
            name='zones_communes',
            field=models.TextField(),
        ),
    ]
