# Generated by Django 5.1.4 on 2025-01-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_residence_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='coproprietaires',
            field=models.ManyToManyField(blank=True, related_name='residences', to='dashboard.coproprietaire', verbose_name='Coproprietaire'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='adresse',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='date_construction',
            field=models.DateField(verbose_name='Construction Date'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='date_dernier_controle',
            field=models.DateField(blank=True, null=True, verbose_name='Last Inspection Date'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nombre_appartements',
            field=models.IntegerField(verbose_name='Number of Apartments'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nombre_etages',
            field=models.IntegerField(verbose_name='Number of Floors'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='superficie_totale',
            field=models.FloatField(verbose_name='Total Area'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='zones_communes',
            field=models.TextField(verbose_name='Common Areas'),
        ),
    ]
