# Generated by Django 5.1.4 on 2025-01-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_residence_coproprietaires_alter_residence_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='coproprietaires',
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='residences',
            field=models.ManyToManyField(blank=True, related_name='coproprietaires', to='dashboard.residence', verbose_name='Residences'),
        ),
    ]
