# Generated by Django 5.1.4 on 2025-01-19 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_residence_coproprietaires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coproprietaire',
            name='residences',
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.residence', verbose_name='Residences'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersyndic_residences', to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_residences', to='dashboard.syndic', verbose_name='Syndic'),
        ),
    ]
