# Generated by Django 5.1.4 on 2025-01-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_coproprietaire_residences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coproprietaire',
            name='residence',
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='residence',
            field=models.ManyToManyField(blank=True, to='dashboard.residence', verbose_name='Residences'),
        ),
    ]
