# Generated by Django 5.1.4 on 2025-01-20 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_coproprietaire_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coproprietaire',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coproprietaire_residences', to='dashboard.residence', verbose_name='Residences'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='supersyndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersyndic_coproprietaires', to='dashboard.supersyndic', verbose_name='SuperSyndic'),
        ),
        migrations.AlterField(
            model_name='coproprietaire',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_coproprietaires', to='dashboard.syndic', verbose_name='Syndic'),
        ),
    ]
