# Generated by Django 5.1.4 on 2025-01-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_coproprietaire_residence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coproprietaire',
            name='residence',
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='residence',
            field=models.ManyToManyField(blank=True, related_name='coproprietaire_residences', to='dashboard.residence', verbose_name='Residences'),
        ),
    ]
