# Generated by Django 5.1.5 on 2025-02-01 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residence', '0001_initial'),
        ('supersyndic', '0001_initial'),
        ('syndic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('residence', models.ManyToManyField(blank=True, related_name='prestataire_residences', to='residence.residence', verbose_name='Residences')),
                ('supersyndic', models.ManyToManyField(blank=True, related_name='supersyndic_prestataires', to='supersyndic.supersyndic', verbose_name='SuperSyndic')),
                ('syndic', models.ManyToManyField(blank=True, related_name='syndic_prestataires', to='syndic.syndic', verbose_name='Syndic')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
