# Generated by Django 5.1.5 on 2025-02-01 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supersyndic', '0001_initial'),
        ('syndic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele_modifie', models.CharField(max_length=255, verbose_name='Modified Model')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('details', models.TextField(verbose_name='Details')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Name')),
                ('adresse', models.TextField(verbose_name='Address')),
                ('nombre_appartements', models.IntegerField(verbose_name='Number of Apartments')),
                ('superficie_totale', models.FloatField(verbose_name='Total Area')),
                ('date_construction', models.DateField(verbose_name='Construction Date')),
                ('nombre_etages', models.IntegerField(verbose_name='Number of Floors')),
                ('zones_communes', models.TextField(verbose_name='Common Areas')),
                ('date_dernier_controle', models.DateField(blank=True, null=True, verbose_name='Last Inspection Date')),
                ('type_chauffage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Heating Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_residences', to=settings.AUTH_USER_MODEL)),
                ('supersyndic', models.ManyToManyField(blank=True, related_name='supersyndic_residences', to='supersyndic.supersyndic', verbose_name='SuperSyndic')),
                ('syndic', models.ManyToManyField(blank=True, related_name='syndic_residences', to='syndic.syndic', verbose_name='Syndic')),
            ],
        ),
    ]
