# Generated by Django 5.1.5 on 2025-02-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Extra Data'),
        ),
    ]
