# Generated by Django 5.1.5 on 2025-02-03 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0002_residence_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
