# Generated by Django 5.1.5 on 2025-02-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0003_residence_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='date_construction',
            field=models.DateField(blank=True, null=True, verbose_name='Construction Date'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nombre_appartements',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Apartments'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nombre_etages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Floors'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='superficie_totale',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Area'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='zones_communes',
            field=models.TextField(blank=True, null=True, verbose_name='Common Areas'),
        ),
    ]
