# Generated by Django 5.1.2 on 2024-11-19 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_supersyndic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supersyndic',
            name='created_at',
        ),
        migrations.AddField(
            model_name='supersyndic',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supersyndic',
            name='license',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_syndic_license', to='home.license'),
        ),
        migrations.AddField(
            model_name='supersyndic',
            name='nom',
            field=models.CharField(default='Default Nom', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supersyndic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_syndic_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
