# Generated by Django 5.1.2 on 2024-11-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_supersyndic_created_at_supersyndic_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supersyndic',
            name='license',
        ),
        migrations.RemoveField(
            model_name='syndic',
            name='license',
        ),
        migrations.AddField(
            model_name='license',
            name='super_syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_syndic_licenses', to='home.supersyndic'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='home.licensebase'),
        ),
        migrations.AlterField(
            model_name='license',
            name='syndic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syndic_licenses', to='home.syndic'),
        ),
    ]
