# Generated by Django 5.1.5 on 2025-02-01 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address')),
                ('nom', models.CharField(max_length=255, verbose_name='last name')),
                ('prenom', models.CharField(max_length=255, verbose_name='first name')),
                ('role', models.CharField(choices=[('Superadmin', 'Superadmin'), ('Syndic', 'Syndic'), ('Coproprietaire', 'Coproprietaire'), ('Prestataire', 'Prestataire'), ('SuperSyndic', 'SuperSyndic')], default='Syndic', max_length=50, verbose_name='role')),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='is active')),
                ('is_superuser', models.BooleanField(choices=[(False, 'Regular User'), (True, 'Super User')], default=False, verbose_name='is superuser')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('status', models.BooleanField(choices=[(False, 'Active'), (True, 'Super Active')], default=False, verbose_name='status')),
                ('commercial', models.CharField(blank=True, max_length=100, null=True, verbose_name='commercial')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='about me')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
