# Generated by Django 5.1.2 on 2024-10-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coproprietaire',
            name='syndic',
        ),
        migrations.RemoveField(
            model_name='coproprietaire',
            name='user',
        ),
        migrations.RemoveField(
            model_name='immeuble',
            name='syndic',
        ),
        migrations.RemoveField(
            model_name='license',
            name='license_base',
        ),
        migrations.RemoveField(
            model_name='license',
            name='syndic',
        ),
        migrations.RemoveField(
            model_name='syndic',
            name='license',
        ),
        migrations.RemoveField(
            model_name='modificationlog',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='syndic',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='user',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='syndic',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appartement',
        ),
        migrations.DeleteModel(
            name='Coproprietaire',
        ),
        migrations.DeleteModel(
            name='Immeuble',
        ),
        migrations.DeleteModel(
            name='LicenseBase',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='ModificationLog',
        ),
        migrations.DeleteModel(
            name='Prestataire',
        ),
        migrations.DeleteModel(
            name='Superadmin',
        ),
        migrations.DeleteModel(
            name='Syndic',
        ),
    ]
