# Generated by Django 5.1.2 on 2024-11-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_role_supersyndic_delete_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperSyndic',
        ),
    ]
