# Generated by Django 5.1.5 on 2025-01-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(choices=[(True, 'Super Active'), (False, 'Active')], default=False, verbose_name='Status'),
        ),
    ]
