# Generated by Django 5.1.5 on 2025-01-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_is_active_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(choices=[(False, 'Regular User'), (True, 'Super User')], default=False, verbose_name='is superuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(choices=[(False, 'Active'), (True, 'Super Active')], default=False, verbose_name='status'),
        ),
    ]
